### ISSUE TITLE
示例项目在引擎中无法编译

### ISSUE THREAD

**Issue by SakuraNeko** [Arisego/livv#1]
引擎版本4.19，VS为2019.2 在启动编译后会出现Error提示，内容为“Live2D cloud not b compiled.”

**Comment by Arisego** [comment]
不好意思我一直没留意Github这边的Issue更新。
我最近对插件进行了重写，这边会Archive掉，如果你感兴趣的话可以试试[更新后的版本](https://github.com/Arisego/UnrealLive2D)。
